### ISSUE TITLE
JSONObject["address"] not found when attempting to start miner

### ISSUE THREAD

**Issue by MarinaGryphon** [apemanzilla/turbokrist#17]
After struggling to build turbokrist (due to a folly of my own), I finally got it to build. I followed the instructions, and everything was going fine until I tried to actually mine. Despite confirming that the address I was putting was correct, I kept getting that error despite trying new/different addresses.

The command I used, and the output, is as follows:
<pre>C:\Users\Moondancer\Krist\turbokrist\turbokrist-cli\build\libs>java -jar turbokrist-cli.jar -a --host kzwow91ylm -w 1072069736:4096
Exception in thread "main" org.json.JSONException: JSONObject["address"] not found.
        at org.json.JSONObject.get(JSONObject.java:471)
        at org.json.JSONObject.getJSONObject(JSONObject.java:636)
        at me.lignum.jkrist.Krist.getAddress(Krist.java:80)
        at me.apemanzilla.krist.turbokrist.MinerOptions.<init>(MinerOptions.java:31)
        at me.apemanzilla.krist.turbokrist.cli.Launcher.main(Launcher.java:108)</pre>

**Comment by apemanzilla** [comment]
@Lignumm, this seems to be an issue with JKrist.

**Comment by Lignumm** [comment]
As far as I know, it'd be either `-host` or `-h` but not `--host`, though I might be wrong. If that doesn't work, try adding `-n http://krist.ceriat.net`.

**Comment by apemanzilla** [comment]
`--host` should be correct. Single character arguments are preceded by a single `-`, and long arguments are preceded by `--`.

**Comment by Lemmmy** [comment]
im so awesome

**Comment by MarinaGryphon** [comment]
Same error with `-n http://krist.ceriat.net`.

**Comment by MarinaGryphon** [comment]
It appears the problem is with my specific address; using the address on the page [Mining Krist](https://github.com/apemanzilla/turbokrist/wiki/Mining-Krist) works just fine. However, I've confirmed multiple times that I'm using the correct address...

**Comment by apemanzilla** [comment]
It's because your address doesn't have any transactions yet. @Lignumm JKrist isn't handling this.

**Comment by Lemmmy** [comment]
this is actually a krist bug technically but also jkrist
